---
title: "Dispos_2019_analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries
```{r include=FALSE}
library(gsubfn)
library(lubridate)
library(openxlsx)
library(data.table)
library(lubridate)
library(readxl)
library(fuzzyjoin)
library(tidyverse)
library(tools)
library(vroom)
library(beepr)

```

## Import Data

```{r}
#df <- fread("G:/CrimJustice/Dispositions by Race and Ethnicity/DOJ Data 2019/Raw Doj Data 2019.csv", colClasses = "character", header = T)

#df <- read.csv("G:/CrimJustice/Dispositions by Race and Ethnicity/DOJ Data 2019/Raw Doj Data 2019.csv", colClasses = "character", header = T)

#top_doj <- read.csv(files[1], colClasses = "character", header = T)

#dsam <- vroom("G:/CrimJustice/Dispositions by Race and Ethnicity/DOJ Data 2019/Raw Doj Data 2019.csv", n_max = 1000, col_types = c(.default = "c"))

dsam <- vroom("G:/CrimJustice/Dispositions by Race and Ethnicity/DOJ Data 2019/Raw DOJ Data 2019-Empty Variables Removed.csv", n_max = 10000, col_types = c(.default = "c"))


#obts <- vroom("G:/CrimJustice/Dispositions by Race and Ethnicity/DOJ Data 2019/DALA_2019_JCC.csv")
```

Diagnostic code using the full dataset isolating columns of interest
```{r}
# allsubs <- vroom("G:/CrimJustice/Dispositions by Race and Ethnicity/DOJ Data 2019/Raw DOJ Data 2019-Empty Variables Removed.csv",
#                  col_select = c(SUBJECT_ID),
#                  #n_max = 100000,
#                  col_types = c(.default = "c"))

#figure out break points for chunking so that no subjects are broken into multiple chunks
# allsubs <- allsubs %>%
#   arrange(SUBJECT_ID)

# distinct_subs <- allsubs %>%
#   distinct(SUBJECT_ID)
# 93,920 distinct subjects


# longsam <- vroom("G:/CrimJustice/Dispositions by Race and Ethnicity/DOJ Data 2019/Raw DOJ Data 2019-Empty Variables Removed.csv",
#                  col_select = c(SUBJECT_ID, CYC_DATE, OFFENSE_DESCR, OFFENSE_TOC),
#                  #n_max = 100000,
#                  col_types = c(.default = "c"))
# beep(4)
# 
# subjs <- longsam %>%
#   distinct(SUBJECT_ID)
# 
# offenses <- longsam %>%
#   count(OFFENSE_DESCR, OFFENSE_TOC)
# 
# yr_ct <- longsam %>%
#   mutate(CYC_DATE = as_date(CYC_DATE)) %>%
#   count(year(CYC_DATE)) 

# long_subcyc <- vroom("G:/CrimJustice/Dispositions by Race and Ethnicity/DOJ Data 2019/Raw DOJ Data 2019-Empty Variables Removed.csv",
#                  col_select = c(SUBJECT_ID, CYC_DATE),
#                  #n_max = 100000,
#                  col_types = c(.default = "c"))
# beep(4)

# subcyc <- long_subcyc %>%
#   mutate(CYC_DATE = as_date(CYC_DATE)) %>%
#   distinct(SUBJECT_ID, CYC_DATE)

#1,773,653 unique subject/cyc_date combinations

# beep(4)  # beep 4 is "work complete". beep 9 would make a good error noise. beep 10 is pleasantly short.

#names(yr_ct) <- c("year", "n")

# yr_ct %>%
#   arrange(desc(year))

# load("G:/CrimJustice/PretrialAssessmentPilot/Complete Charge Code Hierarchy.RData")
# 
# 
# jbsis_missing_offenses <- offenses %>%
#   mutate(offense_orig = str_extract(OFFENSE_DESCR, "^.*\\-"),
#          offense_stat = str_extract(offense_orig, " .*"),
#          offense_stat = gsub(" |-.*", "", offense_stat),
#          offense_orig = gsub(" .*", "", offense_orig),
#          offense = toupper(gsub("\\/|\\(|\\)| |\\.|\\.*|^[A-Z]*|\\\\.*|\\{|\\}","", offense_orig))) %>%
#   unite(join_var, OFFENSE_TOC, offense_stat, offense, remove = F, na.rm = T) %>%
#   inner_join(charge_hier, by = "join_var") %>%
#   filter(jbsis_code == 1000) %>%
#   arrange(desc(n))
# 
# fwrite(jbsis_missing_offenses, "G:/CrimJustice/Dispositions by Race and Ethnicity/DOJ Data 2019/Offenses missing JBSIS codes by frequency in ACHS.csv")

# nonmatching_offenses <- offenses %>%
#   mutate(offense_orig = str_extract(OFFENSE_DESCR, "^.*\\-"),
#          offense_stat = str_extract(offense_orig, " .*"),
#          offense_stat = gsub(" |-.*", "", offense_stat),
#          offense_orig = gsub(" .*", "", offense_orig),
#          offense = toupper(gsub("\\/|\\(|\\)| |\\.|\\.*|^[A-Z]*|\\\\.*|\\{|\\}","", offense_orig))) %>%
#   unite(join_var, OFFENSE_TOC, offense_stat, offense, remove = F, na.rm = T) %>%
#   anti_join(charge_hier, by = "join_var") %>%
#   arrange(desc(n))

#fwrite(nonmatching_offenses, "G:/CrimJustice/Dispositions by Race and Ethnicity/DOJ Data 2019/Offenses not matching charge hierarchy by frequency in ACHS.csv")


```

# Clean achs data
```{r}
names(dsam) <- tolower(names(dsam))

dsam <- dsam %>%
  mutate(across(contains("date"),ymd)) %>%
  mutate(offense_orig = str_extract(offense_descr, "^.*\\-"),
         offense_stat = str_extract(offense_orig, " .*"),
         offense_stat = gsub(" |-.*", "", offense_stat),
         offense_orig = gsub(" .*", "", offense_orig),
         offense = toupper(gsub("\\/|\\(|\\)| |\\.|\\.*|^[A-Z]*|\\\\.*|\\{|\\}","", offense_orig))) %>%
  unite(join_var, offense_toc, offense_stat, offense, remove = F, na.rm = T)



#Filter stp_type_descr to just -- ASK WHAT ALL THE REST MEAN -- is there any reason to keep the others? look into cases that were expunged? any other post-disposition actions that would be relevant? look into what the additional arrest action steps are.
#
dsam <- dsam %>%
  filter(stp_type_descr %in% c("ARREST/DETAINED/CITED", "COURT ACTION"))

#Identify steps with final dispositions. Look at disp_descr to identify dispositions that are not final dispositions (e.g. bench warrant, bail forfeit)

# dsam <- dsam %>%
#   mutate(final_disp = if_else())

#Use step event date as dispo date when there is a disposition but no dispo date (this is all court dispositions and some arrest dispositions)
## step event date is missing for all step types descriptions that are "Additional action" (arrest, court, or custody level) -- unclear what dispositions mean for these
dsam <- dsam %>%
  mutate(dispo_date = case_when(!is.na(disp_date) ~ disp_date,
                                !is.na(disp_descr) ~ stp_event_date),
         arrest_disp = if_else(!is.na(disp_descr) & stp_ori_type_descr == "Arrest", 1, 0),
         court_disp = if_else(!is.na(disp_descr) & stp_ori_type_descr == "Court", 1, 0))

#Remove variables that are not useful
## what are single_source and multi_source?
dsam <- dsam %>%
  select(-c(subject_status, req_gender, race_descr, eye_color_code, eye_color_descr, hair_color_code, hair_color_descr, height, weight, 
            single_source, multi_source, pob_code, pob_name, pob_type,
            conv_offense_order, conv_offense_code, conv_offense_descr, conv_offense_toc, conv_offense_qual_lst, #conv_offense variables are almost never filled out
            disp_offense_code, disp_offense_descr, disp_offense_toc, disp_offense_qual_lst, #disp_offense variables are almost never filled out
            stp_ori_code, stp_ori_descr, stp_ori_cnty_code, stp_ori_type, sent_time_code, sent_loc_code)) %>%  #ori not necessary. ori type, county, sent time, sent loc have additional descriptor variables
  mutate(citizen = case_when(is.na(citizenship_list) ~ NA_real_,
                             grepl("US", citizenship_list) ~ 1,
                             T ~ 0)) %>%
  select(-citizenship_list)


#standardize sentence length
## what does it mean when sentence location is unknown?
## suspended or stayed sentences turn into probation -- how should these be counted? Ask Alexis. Sometimes "JAIL SS", sometimes "IMP SEN SS", sometimes there is both a jail and a suspended jail sentence, does that mean they imposed one and suspended the other?
dsam <- dsam %>%
  mutate(sent_length = as.numeric(sent_length)) %>%
  mutate(sent_length_days = case_when(sent_time_descr == "HOURS" ~ round(sent_length/24),
                                      sent_time_descr == "DAYS" ~ sent_length,
                                      sent_time_descr == "WEEKENDS" ~ sent_length*2,
                                      sent_time_descr == "MONTHS" ~ round(sent_length*365.25/12),
                                      sent_time_descr %in% c("YEARS", "YEARS TO LIFE") ~ round(sent_length*365.25),
                                      sent_length == 0 ~ 0)) %>%
  mutate(sent_life_flag = if_else(grepl("LIFE", sent_time_descr), 1, 0)) %>%
  mutate(sent_prison_flag = if_else(sent_loc_descr %in% c("PRISON", "TOT FIX PRS TRM"), 1, 0),
         sent_jail_flag = if_else(sent_loc_descr %in% c("JAIL", "JAIL OR FINE"), 1, 0),
         sent_probation_flag = if_else(sent_loc_descr %in% c("PROBATION"), 1, 0),
         sent_ex_suspended_flag = if_else(sent_loc_descr %in% c("JAIL SS", "PRISON SS", "PRISON STAYED", "JAIL SS COND", "JAIL OR FINE SS", "FINE SS"), 1, 0),
         sent_imp_suspended_flag = if_else(sent_loc_descr %in% c("IMP SEN SS" ,"SEN SS", "STAYED"), 1, 0),
         sent_concurrent_flag = if_else(sent_loc_descr %in% c("CONCURRENT"), 1, 0))
## for the collapse, will need to cancel out the jail or prison flag and add a probation flag if there is a imp_suspended_flag. Will need to add times unless there is a concurrent_flag.
```

Join charge hierarchy and add prefixes to charge flags
```{r}
# #Join charge hierarchy with offense flags
load("G:/CrimJustice/PretrialAssessmentPilot/Complete Charge Code Hierarchy.RData")
##### if I want to add JBSIS codes to those two most common Infractions that are missing them, would do that here 

dsam <- left_join(dsam, charge_hier, by = "join_var")
      
# Add prefixes to charge flags
dsam <- dsam %>%
  mutate(felony_flag = if_else(offense_toc == "F", 1, 0),
         misd_flag = if_else(offense_toc == "M", 1, 0),
         inf_flag = if_else(offense_toc == "I", 1, 0)) %>%
  mutate_at(vars(contains("flag"), -contains("sent")), funs("arrest" = if_else(. == 1 & stp_ori_type_descr == "Arrest", 1, 0))) %>%
  mutate_at(vars(c(contains("flag"), -contains("sent"), -contains("_arrest"))), funs("court" = if_else(. == 1 & stp_ori_type_descr == "Court", 1, 0))) %>%
  mutate_at(vars(c(contains("flag"), -contains("sent"), -contains("_arrest"), -contains("_court"))), funs("conviction" = if_else(. == 1 & grepl("CONVICTED", disp_descr), 1, 0))) %>%
  rename_at(vars(contains("_conviction")), funs(paste0("conviction_", gsub("_conviction", "", .)))) %>%
  rename_at(vars(contains("_arrest")), funs(paste0("arrest_", gsub("_arrest", "", .)))) %>%
  rename_at(vars(contains("_court")), funs(paste0("court_", gsub("_court", "", .))))

```

Diagnostic code
```{r}
dsam %>%
  filter(arrest_disp ==1) %>%
  count(disp_descr) %>%
  arrange(desc(n))


dsam %>%
  filter(sent_time_descr == "Unknown" & !is.na(sent_length)) %>%
  select(contains("sent_"))

dsam %>%
  filter(!is.na(sent_length)) %>%
  count(sent_time_descr)
  select(contains("sent_"))

dsam %>%
  filter(!is.na(sent_length))%>%
  select(contains("sent_"))

dsam %>%
  filter(!is.na(sent_time_descr) & sent_time_descr != "Unknown") %>%
  filter(is.na(sent_length)) %>%
  select(contains("sent"))

dsam %>%
  filter(!is.na(sent_loc_descr)) %>%
  select(sent_order, sent_loc_descr, sent_length, sent_time_descr)

dsam %>%
  count(sent_order) %>%
  arrange(desc(n))

dsam %>%
  distinct(subject_id, cyc_order, .keep_all = T) %>%
  add_count(subject_id, cyc_date) %>%
  filter(n>1)

dsam %>%
  filter(!is.na(disp_order)) %>%
  group_by(subject_id, cyc_date, cnt_order) %>%
  mutate(n = length(unique(disp_order)),
         ns = length(unique(sent_order))) %>%
  ungroup() %>%
  filter(n>1 & ns>1) 

dsam %>%
  count(stp_type_descr) %>%
  arrange(desc(n))

dsam %>%
  #filter(!is.na(disp_order)) %>%
  group_by(subject_id, cyc_date) %>%
  #mutate(disp_count = length(unique(str_extract(disp_order, "...$")))) %>%
  #add_count(disp_order) %>%
  #filter(disp_count >1) %>%
  #filter(!is.na(sent_order))
  mutate(across(c(contains("_flag")), max),
         jail_count = sum(sent_jail_flag),
         prison_count = sum(sent_prison_flag),
         prob_count = sum(sent_probation_flag),
         imp_count = sum(sent_imp_suspended_flag)) %>%
  #mutate(disp_count = count(disp_order)) %>%
  #distinct(subject_id, cyc_date, .keep_all = T) %>%
  #count(sent_prison_flag, prison_count, sent_jail_flag, jail_count, sent_probation_flag, prob_count, sent_ex_suspended_flag, sent_imp_suspended_flag, imp_count) %>%
  #arrange(desc(n)) %>%
  ungroup() %>%
  filter(imp_count >0) %>%
  filter(imp_count < prison_count + jail_count) %>%
  select(subject_id, cyc_date, disp_order, sent_order, sent_loc_descr, sent_length, sent_time_descr, sent_prison_flag, prison_count, sent_jail_flag, jail_count, sent_probation_flag, prob_count, sent_ex_suspended_flag, sent_imp_suspended_flag, imp_count)


```

Collapse each cycle 
```{r}

## take another pass at this, why can't i get it to stop throwing warnings???

suppressWarnings(
coll_df <- dsam %>%
  #this piece is modified from Noah's code, check if needed
  mutate(arrested_flag = if_else(grepl("Arrest", stp_ori_type_descr), 1, 0),
         filed_flag = if_else(grepl("Court", stp_ori_type_descr), 1, 0),
         convicted_flag =  if_else(grepl("^CONVICTED", disp_descr), 1, 0),
         dismissed_flag = if_else(grepl("DISCH|ACQUIT|DISMISSED|REL|REJ", disp_descr), 1, 0)) %>% 
  
  mutate(across(contains("flag"), ~if_else(is.na(.x), 0, .x))) %>%
 
  mutate(hierarchy = if_else(is.na(hierarchy), 1e6, as.numeric(hierarchy))) %>%
  mutate(sentence_date = if_else(!is.na(sent_order), stp_event_date, as_date(NA_character_))) %>%
  
  ##adjust sentence indicators to account for suspended sentences
  ## first deal with within each count to cancel out suspended jail/prison sentences
  group_by(subject_id, cyc_date, cnt_order) %>%
  
  mutate(sent_ex_suspended_flag = max(sent_ex_suspended_flag),
         sent_imp_suspended_flag = max(sent_imp_suspended_flag),
         sent_prison_flag = if_else(sent_imp_suspended_flag == 1, 0, sent_prison_flag),
         sent_jail_flag = if_else(sent_imp_suspended_flag == 1, 0, sent_jail_flag)) %>%
  
  group_by(subject_id, cyc_date) %>%
  
  #how should concurrent sentences be treated? looked at instances, and appears to be used inconsistently, sometimes when there is no other sentence for it to be concurrent with. could do max instead of sum when there is a concurrent flag, but in cases with more than 2 sentences this may not be correct. probably best to leave as is. 
  mutate(prison_length_days = sum(sent_length_days[sent_prison_flag == 1]),
         jail_length_days = sum(sent_length_days[sent_jail_flag == 1]),
         probation_length_days = sum(sent_length_days[sent_probation_flag == 1]),
         #probation length will be incorrect in cases where there is a suspended sentence with no probation term specified
         sent_probation_flag = if_else(sent_ex_suspended_flag == 1 | sent_imp_suspended_flag == 1, 1, max(sent_probation_flag))) %>%
  mutate(across(matches("sent_.*_flag"), max)) %>%
  
  mutate(across(matches("arrest_.*_flag"), ~if_else(sum(arrested_flag) == 0, 0, max(.x[arrested_flag == 1]))),
         across(matches("court_.*_flag"), ~if_else(sum(filed_flag) == 0, 0, max(.x[filed_flag == 1]))),
         across(matches("conviction_.*_flag"), ~if_else(sum(convicted_flag) == 0, 0, max(.x[convicted_flag == 1])))) %>%
  
  mutate(max_arrest_hier = if_else(sum(arrested_flag) == 0, 1e6, min(hierarchy[arrested_flag == 1])),
         max_court_hier = if_else(sum(filed_flag) == 0, 1e6, min(hierarchy[filed_flag == 1])),
         max_conv_hier = if_else(sum(convicted_flag) == 0, 1e6, min(hierarchy[convicted_flag == 1]))) %>%
  
  mutate(across(c(arrested_flag, filed_flag, convicted_flag, dismissed_flag, arrest_disp, court_disp), max)) %>%
  
  mutate(dispo_date = max(dispo_date, na.rm = T),
         sentence_date = min(sentence_date, na.rm = T)) %>%
  
  #combine qualifiers and remove "NA"s
  mutate(offense_qual_lst = gsub(",NA|NA,","", paste(offense_qual_lst, collapse = ",")),
         offense_qual_lst = if_else(offense_qual_lst == "NA", NA_character_, offense_qual_lst)) %>%
  
  ungroup() %>%
  
  distinct(subject_id, cyc_date, .keep_all = T) 
)

#occasionally there is more than one county listed, or some of the rows list the county as "UNKNOWN". Not very many instances, and it looks like often the first line is not the missing one, so currently not worrying about this. Looks like it is when the arrest and court actions are in different counties. In most of these (already few) cases, the court county is missing. In very few cases there is a different county listed for arrest and court counties. 

coll_df %>%
  select(-c(stp_order, stp_event_date, stp_type_code, stp_type_descr, stp_ori_type_descr, cnt_order, disp_date, offense_code, offense_descr, join_var, offense_toc, disp_order, disp_code, conv_stat_code, conv_stat_descr, sent_order, sent_loc_descr, sent_length, sent_time_descr, offense_orig, offense_stat, offense, charge_level, charge_code, charge, master_charge_description, hierarchy, jbsis_code))


# dsam %>%
#   group_by(cyc_date, subject_id) %>%
#   mutate(n = length(unique(stp_ori_cnty_name))) %>%
#   mutate(counties = paste(stp_ori_cnty_name, collapse = ", ")) %>%
#   ungroup %>%
#   filter(n>1) %>%
#   select(counties, stp_ori_cnty_name, stp_ori_type_descr) 
#   distinct(cyc_date, subject_id, .keep_all = T) %>%
#   count(counties)


```

Old code and diagnostics
```{r}
dsam %>%
  #this piece is modified from Noah's code, check if needed
  mutate(arrested_flag = if_else(grepl("Arrest", stp_ori_type_descr), 1, 0),
         filed_flag = if_else(grepl("Court", stp_ori_type_descr), 1, 0),
         convicted_flag =  if_else(grepl("^CONVICTED", disp_descr), 1, 0),
         dismissed_flag = if_else(grepl("DISCH|ACQUIT|DISMISSED|REL|REJ", disp_descr), 1, 0)) %>%
  filter(subject_id == "35878334") %>%
  mutate(across(matches("arrest_.*_flag"), ~if_else(sum(arrested_flag) == 0, 0, max(.x[arrested_flag == 1]))),
         across(matches("court_.*_flag"), ~if_else(sum(filed_flag) == 0, 0, max(.x[filed_flag == 1]))),
         across(matches("conviction_.*_flag"), ~~if_else(sum(convicted_flag) == 0, 0, max(.x[convicted_flag == 1]))))


dsam %>%
  count(across(matches("arrest_.*_flag")))

dsam %>%
  group_by(subject_id, cyc_date) %>%
  mutate(sent_concurrent_flag = max(sent_concurrent_flag)) %>%
  ungroup() %>%
  filter(sent_concurrent_flag == 1) %>%
  arrange(subject_id, cyc_date)

dsam %>%
  count(across(matches("sent_.*_flag")), sort = TRUE)


#collapse code from pilot
court_dispo <- court_charge %>%
  mutate(disposition_type = ordered(disposition_type, levels = c("Other", "Dismissed", "Not_Guilty", "Nolo_Contendere", "Guilty"))) %>%
  mutate(sentence_type = ordered(sentence_type, levels = c("Other", "Probation", "Jail", "Prison"))) %>%
  group_by(court_case_id) %>%
  mutate(hierarchy = if_else(is.na(hierarchy), 1e6, as.numeric(hierarchy))) %>%
  group_by(court_case_id) %>%
  mutate(disposition_date = max(disposition_date, na.rm = T),
         disposition_type = max(disposition_type),
         conviction_flag = if_else(disposition_type %in% c("Guilty","Nolo_Contendere"), 1, 0),
         sentence_date = if_else(conviction_flag == 1, min(sentence_date, na.rm = T), as_date(NA)),
         sentence_type = max(sentence_type)) %>%
  # mutate(max_court_charge_level = court_charge_level[hierarchy == min(hierarchy)][1],
  #        max_court_charge_code = court_charge_code[hierarchy == min(hierarchy)][1],
  #        max_court_charge = court_charge[hierarchy == min(hierarchy)][1],
  #        max_charge_description = master_charge_description[hierarchy == min(hierarchy)][1],
  #        max_hier = min(hierarchy)) %>%
  mutate_at(vars(contains("flag")), funs(if_else(is.na(.), 0, as.numeric(.)))) %>%
  mutate_at(vars(contains("flag")), funs("count" = sum(.))) %>%
  mutate_at(vars(contains("flag")), max) %>%
  filter(hierarchy == min(hierarchy)) %>%
  ungroup() %>%
  distinct(court_case_id, .keep_all = T)


    # sent_prison_count = case_when(sent_imp_suspended_flag == 0 ~ sum(sent_prison_flag),
    #                                    sent_imp_suspended_flag ==1 & sum(sent_prison_flag) > 0 ~ sum(sent_prison_flag) - 1,
    #                                    sum(sent_prison_flag) == 0 ~ 0),
    #      sent_jail_count = case_when(sent_imp_suspended_flag == 0 | sent_prison_count < sum(sent_prison_flag) ~ sum(sent_jail_flag),
    #                                  sent_imp_suspended_flag == 1 & sum(sent_jail_flag) > 0 ~ sum(sent_jail_flag) - 1,
    #                                  sum(sent_jail_flag) == 0 ~ 0)

coll_df %>%
  count(sent_prison_flag, sent_jail_flag, sent_probation_flag, sent_imp_suspended_flag, sent_ex_suspended_flag) %>%
  arrange(sent_prison_flag, sent_jail_flag, sent_probation_flag, sent_imp_suspended_flag, sent_ex_suspended_flag)

doj_df %>%
  count(sent_prison_flag, sent_jail_flag,  sent_probation_flag, sent_imp_suspended_flag, sent_ex_suspended_flag)%>%
  arrange(sent_prison_flag, sent_jail_flag, sent_probation_flag, sent_imp_suspended_flag, sent_ex_suspended_flag)

coll_df %>%
  group_by(subject_id, cyc_date) %>%
  filter(sum(sent_imp_suspended_flag) >0) %>%
  ungroup()%>%
  count(sent_prison_count, sent_jail_count, sent_prison_flag, sent_jail_flag)

coll_df %>%
  filter(sent_imp_suspended_flag == 1)
```

Sample code from noah for lag
```{r}
df <- tibble(x = 1:3)

df %>%
mutate(y = cumsum(lag(x, default = 0)))

df %>%
mutate(prior_property_flag = cummax(lag(property_flag, default = 0)),
prior_hierarchy = cummin(lag(hierarchy, default = 1e6)))
```

Collapse historical cycles by person
```{r}
doj_df <- coll_df %>%
  select(-c(stp_order, stp_event_date, stp_type_code, stp_type_descr, stp_ori_type_descr, cnt_order, disp_date, offense_code, offense_descr, join_var, offense_toc, disp_order, disp_code, conv_stat_code, conv_stat_descr, sent_order, sent_loc_descr, sent_length, sent_time_descr, offense_orig, offense_stat, offense, charge_level, charge_code, charge, master_charge_description, hierarchy, jbsis_code, special_flag, serious_felony_flag, violent_felony_flag, violent_psa_flag, capital_flag, dv_flag, marijuana_flag, sup_vio_flag, fta_flag, sex_flag, dui_flag, sb10_dui_flag, restrain_flag, sb10_onduty_inel_flag, sb10_dui_flag, property_flag, drug_flag, dv_possible_flag, felony_flag, misd_flag, inf_flag))
  

  
#most individuals have 1 2019 disposition. A couple have none, and some have more than 1. Unit of analysis should be the disposition. Separate out the non-current dispositions and collapse them down to the person, and then attach the collapsed criminal histories by person to each current disposition. 

dispos_2019 <- doj_df %>%
  filter(year(dispo_date) == 2019)

histories <- doj_df %>%
  filter(year(dispo_date) != 2019) #what about rows with no dispo date? do these all not have a disposition? why are they in this dataset? should I include these for arrests?
  
hist_collapse <- histories %>%
  group_by(subject_id) %>%
  mutate(days_prior_prison = sum(prison_length_days),
         days_prior_jail = sum(jail_length_days),
         days_prior_probation = sum(probation_length_days)) %>%
    
  #combine qualifiers and remove "NA"s
  mutate(prior_quals = gsub(",NA|NA,","", paste(offense_qual_lst, collapse = ",")),
         prior_quals = if_else(prior_quals == "NA", NA_character_, prior_quals)) %>%
  
  mutate(prior_dispo_date = max(dispo_date, na.rm = T), #keep the most recent prior disposition date
         citizen = if_else(is.na(citizen), 0, citizen),
         prior_citizen = max(citizen, na.rm = T),
         age_first_dispo = min(cyc_age, na.rm = T)) %>%

  #create counts for each flag
  mutate(across(contains("flag"), sum, .names = "prior_{.col}_count")) %>%
  mutate(across(contains("hier"), min, .names = "prior_{.col}")) %>%
  
  ungroup() %>%
  distinct(subject_id, .keep_all = T) %>%

  select(subject_id, contains("prior"), age_first_dispo)
  
  
#join histories to 2019 dispositions
doj_df <- dispos_2019 %>%
  left_join(hist_collapse)

#fwrite(doj_df, "G:/CrimJustice/Dispositions by Race and Ethnicity/DOJ Data 2019/Cleaned DOJ data small sample 1.4.2021.csv")

#should add some kind of indicator for concurrent cases, or additional 2019 cases. Or should add earlier 2019 cases to criminal history for later cases in 2019? yeesh.
```

Diagnostics
```{r}


doj_df %>%
  mutate(dispo_2019 = if_else(year(dispo_date) == 2019, 1, 0)) %>%
  count(dispo_2019)
  group_by(subject_id) %>%
  mutate(current_count = sum(dispo_2019, na.rm = T)) %>%
  ungroup() %>%
  distinct(subject_id, .keep_all = T) %>%
  count(current_count)
  
  
doj_df %>%
  count(yr = year(dispo_date)) %>%
  arrange(desc(n)) %>%
  mutate(yrtf = if_else(yr == 2019, T, F))

doj_df %>%
  distinct(subject_id)

str_replace_na(c(1, 2, 3, NA_character_), replacement = 0)

histories %>%
  select(contains("flag"))
  select(contains("hier"))
dsam %>%
  select(contains("date"))

dsam %>%
  filter(stp_ori_type_descr == "Court")

dsam %>%
  count(subject_id, cyc_order)

summary(dsam$stp_event_date)

dsam %>%
  filter(subject_id == "1000093" & cyc_order == "102000000000")

dsam %>%
  filter(!is.na(stp_event_date) & !is.na(disp_date)) %>%
  select(stp_event_date, disp_date)

dsam %>%
  filter(disp_code == "1008")


dsam %>%
  filter(disp_date > as_date("2019-01-01")) %>%
  arrange(stp_event_date) %>%
  distinct(subject_id, cyc_order, .keep_all = T)

dsam %>%
  filter(offense_code == "00001")

dsam %>%
  filter(!is.na(disp_descr) & is.na(disp_date)) %>%
  count(stp_ori_type_descr)

dsam %>%
  filter(stp_event_date == disp_date)

dsam %>%
  filter(!is.na(disp_date)) %>%
  count(stp_type_descr) %>%
  arrange(desc(n))

dsam %>%
  filter(stp_ori_type_descr == "Court" & !is.na(disp_descr)) %>%
  count(stp_type_descr, disp_descr) %>%
  arrange(desc(n))

#court dispositions do not use disp_date! use stp_event_date instead.
#not all disp_descr look like they are final dispositions, need to sort out which ones are (e.g. bail forfeited, bench warrant)

dsam %>%
  count(stp_type_descr) %>%
  arrange(desc(n))

dsam %>%
  filter(grepl("PROS", disp_descr)) %>%
  filter(is.na(disp_date)) %>%
  count(stp_ori_type_descr, stp_type_descr, disp_descr)



```

```{r}
dsam %>%
  count(stp_type_descr, disp_descr) %>%
  arrange(desc(n))

dsam %>%
  count(stp_ori_type_descr, stp_type_descr) %>%
  arrange(desc(n))

dsam %>%
  filter(stp_type_descr == "CDC CUSTODY")

dsam %>%
  filter(stp_type_descr %in% c("ARREST/DETAINED/CITED", "COURT ACTION")) %>%
  count(disp_descr) %>%
  arrange(desc(n))
```

